console.log(1==1);
console.log(1===1);
console.log('1'==1);
console.log('1'===1);
console.log(true==1);
console.log(true===1);
console.log(true=='1');
console.log(true=='true');
console.log(false==' ');
console.log(false==[]);
